### ISSUE TITLE
Teaming-up with  zanyants/mvp.xml?

### ISSUE THREAD

**Issue by jbaehr** [keimpema/Mvp.Xml.NetStandard#1]
Hi,

What do you think about rebasing your changes on top of 
[zanyants/mvp.xml](https://github.com/zanyants/mvp.xml)? They have imported the whole history of the original codeplex project in their `master` and a few other enhancements in a `contrib` branch.

Having a single nuget supporting several flavours of .NET is much nicer then different packages for .NET-Standard and .NET-Framework. And both "worlds" could benefit from fixes like zanyants/mvp.xml#1.

**Comment by keimpema** [comment]
I do not intent to pursue that course. Sorry.
And I should have responded waaaay earlier! :flushed:
