### ISSUE TITLE
strong sign the assembly

### ISSUE THREAD

**Issue by jakubmisek** [keimpema/Mvp.Xml.NetStandard#3]
Please add strong signature to the assembly and the corresponding NuGet so it can be used on .NET Framework.

Will prepare PR if it helps.

**Comment by keimpema** [comment]
If you could create a PR for this, that would be great.

**Comment by jakubmisek** [comment]
@keimpema thanks, PR #4 ready :)

**Comment by bfistein** [comment]
This would be really great to have @keimpema, any indication on an ETA for this?

**Comment by jakubmisek** [comment]
signed package is available at https://www.nuget.org/packages/Mvp.Xml.NetStandard.Signed
