### ISSUE TITLE
Crashing on Android: Could not load assembly 'mvp.xml' during startup registration

### ISSUE THREAD

**Issue by kripper** [keimpema/Mvp.Xml.NetStandard#5]
Mvp.Xml.NetStandard crashes on Android/Xamarin with error:
```Could not load assembly 'mvp.xml' during startup registration```

See: https://github.com/peachpiecompiler/peachpie/issues/785

**Comment by keimpema** [comment]
Closing for now since the referenced peachpiecompiler issue is also closed. Seems not an issue anymore.
